#help=...
#type=...
#output=...
#options=...

## constructor and initializer of session
# @param options algorithm options
# @return algorithm object : environment options, status
def MyAlgorithm(options) :
    ...
return algorithm

## first design building.
# @param algorithm object handling options, status, ...
# @param d the number of variables all set in [0,1]
def getInitialDesign(algorithm,d) :
    ...
return X

## iterated design building.
# @param algorithm object handling options, status, ...
# @param X matrix of current doe variables (in [0,1])
# @param Y matrix of current results
# @return matrix of next doe step
def getNextDesign(algorithm,X,Y) :
    ...
return X

## final analysis. All variables are set in [0,1].
# @param algorithm object handling options, status, ...
# @return HTML string of analysis
def displayResults(algorithm,X,Y) :
    ...
return html

...
