%title:...
%help:...
%author:...
%type:...
%output:...
%options:...
%options.help:...

% constructor and initializer of algorithm
% @return algorithm object : options, status
function algorithm = MyAlgorithm(options)
    ...
end
